# defines
#  PCRE2_FOUND
#  PCRE2_INCLUDE_DIRS
#  PCRE2_LIBRARIES

find_package(PkgConfig)
if (PKG_CONFIG_FOUND)
	pkg_check_modules(PC_PCRE2 QUIET libpcre2-8)
endif()

set(PCRE2_DEFINITIONS ${PC_PCRE2_CFLAGS_OTHER})

find_path(PCRE2_INCLUDE_DIR pcre2.h
	PATHS ${PC_PCRE2_INCLUDEDIR} ${PC_PCRE2_INCLUDE_DIRS}
	PATH_SUFFIXES)

list(APPEND PCRE2_NAMES pcre2-8)

find_library(PCRE2_LIBRARY NAMES ${PCRE2_NAMES}
	PATHS ${PC_PCRE2_LIBDIR} ${PC_PCRE2_LIBRARY_DIRS})

set(PCRE2_LIBRARIES ${PCRE2_LIBRARY})
set(PCRE2_INCLUDE_DIRS ${PCRE2_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Pcre2 DEFAULT_MSG
	PCRE2_LIBRARY PCRE2_INCLUDE_DIR)

mark_as_advanced(PCRE2_INCLUDE_DIR PCRE2_LIBRARY)
